### ISSUE TITLE
Challenge fails 'Error: socket hang up' ECONNRESET 

### ISSUE THREAD

**Issue by JonDum** [ZencashOfficial/secnodetracker#20]
It looks like the SEA challenge server isn't responding fast enough and the connection is timing out

```
2017-12-03 19:19:09 GMT -- Start challenge. 9274
Using zcAasERYm2YxUMuvYctoXGziFRsF8BwocETzenGgKhRwaua1Y6Xac3qk8xTJ6kmeMZjeSxo2toDMLmwtfSWqthGGZMpsrRb for challenge. bal=1.0994
OperationId=opid-bce60fa2-94f8-4e54-8194-99ec0c768afd
2017-12-03 19:19:19 GMT -- Elapsed challenge time=10  status=executing
2017-12-03 19:19:29 GMT -- Elapsed challenge time=20  status=executing
2017-12-03 19:19:39 GMT -- Elapsed challenge time=30  status=executing
2017-12-03 19:19:49 GMT -- Elapsed challenge time=40  status=executing
2017-12-03 19:19:59 GMT -- Elapsed challenge time=50  status=executing
2017-12-03 19:20:09 GMT -- Elapsed challenge time=60  status=executing
2017-12-03 19:20:12 GMT -- Stat check: connected to:ts1.sea blocks:215903 peers:11 bal:1.0994 isValidBal:true queueDepth:0 lastChalBlock:215329 lastExecSec:469.01
2017-12-03 19:20:59 GMT -- Elapsed challenge time=110  status=executing
2017-12-03 19:21:09 GMT -- Elapsed challenge time=120  status=executing
2017-12-03 19:21:19 GMT -- Elapsed challenge time=130  status=executing
2017-12-03 19:26:12 GMT -- Stat check: connected to:ts1.sea blocks:215904 peers:12 bal:1.0994 isValidBal:true queueDepth:0 lastChalBlock:215329 lastExecSec:469.01
challenge error
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
challenge error
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
challenge error
2017-12-03 19:32:12 GMT -- Stat check: connected to:ts1.sea blocks:215908 peers:13 bal:1.0992 isValidBal:true queueDepth:0 lastChalBlock:215329 lastExecSec:469.0
```

**Comment by ADumaine** [comment]
I checked the logs and the stats listed above were logged ok.  The challenge never completed.   The 'challenge error' seems to be a socket hang up between the tracker and zen.  

The two challenges for that node that did pass have very long run times: 779 and 469.  The node does not appear to have the resources to run a challenge.  If memory is less than 4GB trying adding another GB to the swap.  

Also the node reports '0 @ 2.00GHz ' and '24 cores'.  The number of cores seems odd.  Usually there is one or two.  Perhaps the vps provider has something misconfigured.

**Comment by ADumaine** [comment]
Closed for no activity.  Reopen if needed.
