### ISSUE TITLE
pm2 issue

### ISSUE THREAD

**Issue by satnamsidhu** [ZencashOfficial/secnodetracker#22]
STACK TRACE
TypeError: Cannot read property 'trim' of null
    at Object. (/home/sss/zencash/secnodetracker/app.js:51:41)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
    at Object. (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:73:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

CODE LINES

let fqdn = local.getItem('fqdn') || null;
if (fqdn) fqdn = fqdn.trim();
let stkaddr = local.getItem('stakeaddr').trim();
let ident = { "nid": nodeid, "stkaddr": stkaddr, "fqdn": fqdn };
ident.con = { home: home, cur: curServer }

**Comment by ADumaine** [comment]
Have you run the setup tracker and entered your node's FQDN (full hostname)?
In the secnodetracker folder run: node setup

**Comment by ADumaine** [comment]
no response
